develop:
  extends:
    file: base.yml
    service: base
  container_name: gfw-terrai-alerts-api-develop
  environment:
    NODE_ENV: dev
    CARTODB_USER: wri-01
  command: develop
  volumes:
    - ./app:/opt/gfw-terrai-alerts-api/app
