develop:
  extends:
    file: base.yml
    service: base
  container_name: gfw-terrai-alerts-api-develop
  environment:
    NODE_ENV: dev
    CARTODB_USER: wri-01
    API_GATEWAY_URL: http://mymachine:9000
    API_VERSION: v1
    DATASET_TERRAI_ID: 668cedb0-b5c8-49c0-9c37-b2eadd46ac17
  command: develop
  volumes:
    - ./app:/opt/gfw-terrai-alerts-api/app
